### ISSUE TITLE
question about write drl file

### ISSUE THREAD

**Issue by huahuayu** [aasaru/drools-training#1]
hi, I tooked your drools course in udemy, I came up a case in here  https://github.com/huahuayu/drools, which is to use rules to determine the final price for e-commerce. But I got below error I tried and searched but don't know how to fix it, would you please take a look of my project, thank you!

![image](https://user-images.githubusercontent.com/1725060/60771148-0cf13e80-a116-11e9-99e7-6dbd7427980e.png)

**Comment by aasaru** [comment]
Hi!
Sorry I don't follow questions asked here, please ask them via Udemy.
One mistake I see from the screen shot is that you  define variable $order and try to use it on the same line. So instead of:
$order:Order($order.getCustomer().getType() == "3");
you should have:
$order:Order(getCustomer().getType() == "3");
or even better:
$order:Order(customer.type == "3");
If you have any more questions, please ask via Udemy.
